# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_IdentificacionFallas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_IdentificacionFallas(object):
    def setupUi(self, MainWindow_IdentificacionFallas):
        MainWindow_IdentificacionFallas.setObjectName("MainWindow_IdentificacionFallas")
        MainWindow_IdentificacionFallas.resize(1422, 705)
        MainWindow_IdentificacionFallas.setStyleSheet("QMainWindow{\n"
"background-color:rgb(15,15,15);    /*fondo de todo el widget*/\n"
"    }\n"
"\n"
"QWidget{\n"
"    background-color:rgb(15,15,15);    /*fondo de todo el widget*/\n"
"    }\n"
"    \n"
"    \n"
"    QMenuBar{\n"
"    color: rgb(66,200,195);\n"
"    background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 rgb(0,91,65), stop:1 rgb(15,15,15)) ;\n"
"}   /*nodifica la barra del menu pero no su contenido*/\n"
"    \n"
"    \n"
"    QMenuBar::item{\n"
"    padding:0px 4px;\n"
"    border-radius:10px;\n"
"    padding-right: 20px;\n"
"    }  /*Modifica contenido del menu*/\n"
"    \n"
"    QMenuBar::item:selected{\n"
"    background-color:rgb(35,35,35);\n"
"    } /*Cambia el color del elemento del menu que este seleccionado */\n"
"    \n"
"    QMenuBar::item:disabled {\n"
"    background-color: rgb(15, 15, 15);\n"
"    color: rgb(35,35,35)\n"
"    }\n"
"    \n"
"    \n"
"    QMenu{\n"
"    color: rgb(66,200,195);\n"
"    background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 rgb(15,15,15), stop:1 rgb(35,35,35)) ;\n"
"    }   /*nodifica la barra del menu pero no su contenido*/\n"
"    \n"
"    \n"
"    QMenu::item{\n"
"    padding:0px 4px;\n"
"    border-radius:10px;\n"
"    padding-right: 20px;\n"
"    \n"
"    }  /*Modifica contenido del menu*/\n"
"    \n"
"    QMenu::item:selected{\n"
"    background-color:rgb(35,35,35);\n"
"    } /*Cambia el color del elemento del menu que este seleccionado */\n"
"    \n"
"    QMenu::item:disabled {\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(15,15,15)\n"
"    }\n"
"    \n"
"    \n"
"    \n"
"    QLabel{\n"
"    Color:white;\n"
"    }\n"
"    \n"
"    \n"
"    QPushButton{\n"
"    background-color: rgb(0,129,112);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(0,91,65);\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    } /*configuracion general del boton*/\n"
"    \n"
"    QPushButton:hover{\n"
"    background: qradialgradient(cx: 0.5, cy:0.5, radius:1 ,fx:0.5, fy:0.5 , stop:0 rgb(0,129,112), stop: 1 rgb(0,91,65));\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: transparent;\n"
"    color: white;\n"
"    } /*Configuracion del boton cuando se le pasa el mouse por encima*/\n"
"    \n"
"    QPushButton:pressed {\n"
"    background-color:rgb(0,91,65);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: white;\n"
"    color: white;\n"
"    }/*Configuracion del botob cuando se le hace clik*/\n"
"    \n"
"    \n"
"    QPushButton:disabled {\n"
"    background-color: rgb(35, 35, 35);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: transparent;\n"
"    color: rgb(15,15,15);\n"
"} \n"
"    \n"
"    \n"
"    \n"
"    QComboBox{\n"
"    border: 2px rgb(0,129,112);\n"
"    border-radius: 5px;\n"
"    background-color:rgb(35,35,35);\n"
"    color: white;\n"
"    } /*como aparece en pantalla*/\n"
"    \n"
"    QComboBox:hover{\n"
"    background: qradialgradient(cx: 0.5, cy:0.5, radius:1 ,fx:0.5, fy:0.5 , stop:0 rgb(35,35,35), stop: 1 rgb(0,91,65));\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: transparent;\n"
"    color: white;\n"
"    } \n"
"    \n"
"    QComboBox::drop-down {\n"
"    subcontrol-origin:padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    }\n"
"    \n"
"    QComboBox QAbstractItemView{\n"
"    border: 2px ;\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(x1:0,y1:0,x2:0,y2:2, stop:0 rgb(35,35,35), stop:1 rgb(0,91,65)) ;;\n"
"    color: white;\n"
"    \n"
"    } /*Modifica el menu desplegable del Combo box*/\n"
"    \n"
"    \n"
"    QToolButton{\n"
"    background-color: rgb(0,129,112);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color:transparent;\n"
"    color: white;\n"
"    }\n"
"    \n"
"    QCheckBox {\n"
"    color: white;\n"
"    }\n"
"    \n"
"    QCheckBox::indicator:unchecked{\n"
"    background-color: rgb(0,129,112);\n"
"    border-radius: 3px;\n"
"    } /*Cambia el color del cuadrado cuando no esta seleccionado*/\n"
"    \n"
"    QCheckBox::indicator:disabled{\n"
"    background-color: rgb(35,35,35);\n"
"    border-radius: 3px;\n"
"    }\n"
"\n"
"    QRadioButton {\n"
"    color: white;\n"
"    }\n"
"    \n"
"    QRadioButton::indicator:unchecked{\n"
"    background-color: rgb(0,129,112);\n"
"    border-radius: 6px;\n"
"    }/*Cambia el color del cuadrado cuando no esta seleccionado*/\n"
"    \n"
"    QListWidget{\n"
"    Color: white;\n"
"    background-color: rgb(35,35,35);\n"
"    border-radius: 5px;\n"
"    border-color: transparent;\n"
"    }\n"
"    \n"
"    \n"
"    /* Tab;al */\n"
"    \n"
"    /* view */\n"
"    QTableView{\n"
"    Color: white;\n"
"    background-color: rgb(15,15,15);\n"
"    }\n"
"    \n"
"    QTableView QHeaderView::section {\n"
"     background-color: rgb(35,35,35);\n"
"     border: 1px solid rgb(0,91,65);\n"
"    color:white;\n"
"    }\n"
"    \n"
"    QTableView QTableCornerButton::section {\n"
"     background-color: rgb(35,35,55);\n"
"     border: 1px solid rgb(0,91,65);\n"
"    }\n"
"    \n"
"    QTableView::item {\n"
"     border: 1px solid white;\n"
"    }\n"
"    \n"
"    /*Widget*/\n"
"    QTableWidget{\n"
"    Color: white;\n"
"    background-color: rgb(15,15,15);;\n"
"    }\n"
"    \n"
"    QTableWidget QHeaderView::section {\n"
"     background-color: rgb(35,35,35);\n"
"     border: 1px solid rgb(0,91,65);\n"
"    color:white;\n"
"    }\n"
"    \n"
"    QTableWidget QTableCornerButton::section {\n"
"     background-color: rgb(35,35,35);\n"
"     border: 1px solid rgb(0,91,65);\n"
"    }\n"
"    \n"
"    QTableWidget::item::hover{\n"
"    background: qradialgradient(cx: 0.5, cy:0.5, radius:4 ,fx:0.5, fy:0.5 , stop:0 rgb(15,15,15), stop: 1 rgb(0,91,65));\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: transparent;\n"
"    color: white;\n"
"    }\n"
"\n"
"    QTableWidget::item::selected{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(66,200,195);\n"
"    color: white;\n"
"    }\n"
"    \n"
"    /* barras deslizante */\n"
"    \n"
"    /* Vertical */\n"
"    QScrollBar:vertical {\n"
"     border: 1px solid transparent;  /* Cambia el color del borde de la barra deslizante vertical */\n"
"     background:  rgb(225,255,255);  /* Cambia el color de fondo de la barra deslizante vertical */\n"
"    width: 12px;  /* Cambia el ancho de la barra deslizante vertical */\n"
"    margin: 0px 0px 0px 0px;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"    background: rgb(35,35,35);  /* Cambia el color del cuadrado */\n"
"    border-radius: 4px;\n"
"    }\n"
"    QScrollBar::add-line:vertical { /*oculta flechas superior*/\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:vertical { /*oculta flechas inferior*/\n"
"     height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    }\n"
"    \n"
"    QScrollBar::handle:hover:vertical {\n"
"        background: rgb(0,129,112);\n"
"    }\n"
"    \n"
"    /* Horizontal*/\n"
"    QScrollBar:horizontal {\n"
"     border: 1px solid transparent;  /* Cambia el color del borde de la barra deslizante vertical */\n"
"     background:solid rgb(255,255,255);  /* Cambia el color de fondo de la barra deslizante vertical */\n"
"    height: 12px;  /* Cambia el ancho de la barra deslizante vertical */\n"
"    margin: 0px 0px 0px 0px;\n"
"    }\n"
"    QScrollBar::handle:horizontal {\n"
"    background: rgb(35,35,35);  /* Cambia el color del cuadrado */\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"     border: 1px solid transparent;\n"
"    }\n"
"    \n"
"    QScrollBar::add-line:horizontal { /*oculta flechas superior*/\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:horizontal { /*oculta flechas inferior*/\n"
"     height: 0 px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"    }\n"
"    \n"
"    QScrollBar::handle:hover:horizontal {\n"
"    background: rgb(0,129,112);\n"
"    }\n"
"    \n"
"    /*tree*/\n"
"    QTreeWidget{\n"
"    Color: white;\n"
"    }\n"
"    \n"
"    QTreeWidget QHeaderView::section {\n"
"     background-color: rgb(35,35,35);\n"
"     border: 1px solid rgb(0,129,112);\n"
"    color:white;\n"
"    }\n"
"    \n"
"    /*line edit*/\n"
"    QLineEdit{\n"
"    background-color: rgb(35,35,35);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(0,91,65);\n"
"    color: white;\n"
"    padding: 3px;\n"
"    }\n"
"\n"
"    QLineEdit:disabled {\n"
"        background-color: rgb(15,15,15);\n"
"        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 5px;\n"
"        border-color: rgb(0,91,65);;\n"
"        color: white;\n"
"        padding: 3px;\n"
"    }\n"
"\n"
"    QLineEdit:read-only {\n"
"        background-color: rgb(15,15,15);\n"
"        border-style: outset;\n"
"        border-width: 2px;\n"
"        border-radius: 5px;\n"
"        border-color: rgb(0,91,65);;\n"
"        color: white;\n"
"        padding: 3px;\n"
"    }\n"
"    /*spin box*/\n"
"    \n"
"    QSpinBox {\n"
"     border: 2px solid transparent; /* Ajusta el tipo de borde y el color  */\n"
"     border-radius: 5px;\n"
"     background-color: rgb(0,129,112);\n"
"     color: white;\n"
"    }\n"
"    \n"
"    QSpinBox::up-button{\n"
"     subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    \n"
"    }\n"
"    \n"
"     QSpinBox::down-button {\n"
"     subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    \n"
"    }\n"
"    \n"
"    QDateEdit{\n"
"    background-color: rgb(0,129,112);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(0,91,65);\n"
"    color: white;\n"
"    }\n"
"    \n"
"    QDateTimeEdit{\n"
"    background-color: rgb(0,129,112);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(0,91,65);\n"
"    color: white;\n"
"    }\n"
"    \n"
"    QTimeEdit{\n"
"    background-color: rgb(0,129,112);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: rgb(0,91,65);\n"
"    color: white;\n"
"    }\n"
"\n"
"\n"
"    QToolBox::tab{\n"
"    background-color: rgb(35,35,35);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color: transparent;\n"
"    color: rgb(66,200,195);\n"
"    }\n"
"\n"
"    QToolBox::tab:selected{\n"
"   background-color: rgb(0,129,112);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    border-color:transparent;\n"
"    color: white;\n"
"    }\n"
"\n"
"    QTabWidget::pane {\n"
"        border: 0.5px solid rgb(0,91,65);\n"
"        top:-1px;  \n"
"      } \n"
"      \n"
"    QTabBar::tab {\n"
"        background: rgb(35, 35, 35); \n"
"        border: 0.5px solid rgb(0,91,65); \n"
"        padding: 5px;\n"
"        color: white;\n"
"      } \n"
"      \n"
"    QTabBar::tab:selected { \n"
"        background:  rgb(0,129,112);; \n"
"        margin-bottom: -1px;\n"
"      }")
        self.centralwidget = QtWidgets.QWidget(MainWindow_IdentificacionFallas)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setMaximumSize(QtCore.QSize(251, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_DescargaInf = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_DescargaInf.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DescargaInf.sizePolicy().hasHeightForWidth())
        self.pushButton_DescargaInf.setSizePolicy(sizePolicy)
        self.pushButton_DescargaInf.setObjectName("pushButton_DescargaInf")
        self.gridLayout_3.addWidget(self.pushButton_DescargaInf, 1, 0, 1, 1)
        self.pushButton_CargaDatos = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_CargaDatos.setObjectName("pushButton_CargaDatos")
        self.gridLayout_3.addWidget(self.pushButton_CargaDatos, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(686, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_graficarcluster = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_graficarcluster.setObjectName("pushButton_graficarcluster")
        self.gridLayout.addWidget(self.pushButton_graficarcluster, 15, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 11, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 16, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 13, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 10, 0, 1, 1)
        self.pushButton_escalar = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_escalar.setObjectName("pushButton_escalar")
        self.gridLayout.addWidget(self.pushButton_escalar, 9, 0, 1, 1)
        self.pushButton_grafCodo = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_grafCodo.setObjectName("pushButton_grafCodo")
        self.gridLayout.addWidget(self.pushButton_grafCodo, 12, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 14, 0, 1, 1)
        self.pushButton_correr_actual = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_correr_actual.setObjectName("pushButton_correr_actual")
        self.gridLayout.addWidget(self.pushButton_correr_actual, 6, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 8, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout_6.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        MainWindow_IdentificacionFallas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_IdentificacionFallas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1422, 16))
        self.menubar.setObjectName("menubar")
        MainWindow_IdentificacionFallas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_IdentificacionFallas)
        self.statusbar.setObjectName("statusbar")
        MainWindow_IdentificacionFallas.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_IdentificacionFallas)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_IdentificacionFallas)

    def retranslateUi(self, MainWindow_IdentificacionFallas):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_IdentificacionFallas.setWindowTitle(_translate("MainWindow_IdentificacionFallas", "MainWindow"))
        self.pushButton_DescargaInf.setText(_translate("MainWindow_IdentificacionFallas", "Actualizar información?"))
        self.pushButton_CargaDatos.setText(_translate("MainWindow_IdentificacionFallas", "Cargar información actual"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow_IdentificacionFallas", "Cargar Datos"))
        self.pushButton_graficarcluster.setText(_translate("MainWindow_IdentificacionFallas", "Graficar Clusters"))
        self.comboBox_3.setItemText(0, _translate("MainWindow_IdentificacionFallas", "K-MEANS"))
        self.comboBox.setItemText(0, _translate("MainWindow_IdentificacionFallas", "Google"))
        self.comboBox.setItemText(1, _translate("MainWindow_IdentificacionFallas", "Youtube"))
        self.comboBox.setItemText(2, _translate("MainWindow_IdentificacionFallas", "TikTok"))
        self.comboBox.setItemText(3, _translate("MainWindow_IdentificacionFallas", "Instagram"))
        self.label_5.setText(_translate("MainWindow_IdentificacionFallas", "Escalar datos"))
        self.label.setText(_translate("MainWindow_IdentificacionFallas", "Destino"))
        self.label_4.setText(_translate("MainWindow_IdentificacionFallas", "% campos vacios"))
        self.label_8.setText(_translate("MainWindow_IdentificacionFallas", "número de clusters"))
        self.label_7.setText(_translate("MainWindow_IdentificacionFallas", "CLASIFICACION"))
        self.pushButton_escalar.setText(_translate("MainWindow_IdentificacionFallas", "Grafico escalado"))
        self.pushButton_grafCodo.setText(_translate("MainWindow_IdentificacionFallas", "Gráfica codo"))
        self.lineEdit_2.setText(_translate("MainWindow_IdentificacionFallas", "3"))
        self.pushButton_correr_actual.setText(_translate("MainWindow_IdentificacionFallas", "Histograma"))
        self.comboBox_2.setItemText(0, _translate("MainWindow_IdentificacionFallas", "MinMaxScaler"))
        self.comboBox_2.setItemText(1, _translate("MainWindow_IdentificacionFallas", "StandardScaler"))
        self.comboBox_2.setItemText(2, _translate("MainWindow_IdentificacionFallas", "RobustScaler"))
        self.comboBox_2.setItemText(3, _translate("MainWindow_IdentificacionFallas", "MaxAbsScaler"))
        self.comboBox_2.setItemText(4, _translate("MainWindow_IdentificacionFallas", "Normalizer"))
        self.comboBox_2.setItemText(5, _translate("MainWindow_IdentificacionFallas", "QuantileTransformer"))
        self.lineEdit.setText(_translate("MainWindow_IdentificacionFallas", "30"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow_IdentificacionFallas", "Análisis Clustering"))
        self.pushButton.setText(_translate("MainWindow_IdentificacionFallas", "Gráfico señales"))
        self.pushButton_2.setText(_translate("MainWindow_IdentificacionFallas", "Capa de falla"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow_IdentificacionFallas", "Análisis de la Falla"))
